image: "debian:"

stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy:
  type: deploy
  stage: deploy
  environment: staging
  script:
  - ssh $LOGIN bash --login "./deploy.sh"
  only:
  - uluwatu
